//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControleTarefas.Utilitarios.Messages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BusinessMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BusinessMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ControleTarefas.Utilitarios.Messages.BusinessMessages", typeof(BusinessMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo &quot;{0}&quot; está inválido..
        /// </summary>
        public static string CampoInvalido {
            get {
                return ResourceManager.GetString("CampoInvalido", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to O campo &quot;{0}&quot; não foi encontrado..
        /// </summary>
        public static string CampoNaoEncontrado
        {
            get
            {
                return ResourceManager.GetString("CampoNaoEncontrado", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to O campo &quot;{0}&quot; é obrigatório..
        /// </summary>
        public static string CampoObrigatorio {
            get {
                return ResourceManager.GetString("CampoObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo &quot;{0}&quot; deve possuir no máximo {1} caracteres..
        /// </summary>
        public static string CampoTamanhoMaximo {
            get {
                return ResourceManager.GetString("CampoTamanhoMaximo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo &quot;{0}&quot; deve possuir no mínimo {1} caracteres..
        /// </summary>
        public static string CampoTamanhoMinimo {
            get {
                return ResourceManager.GetString("CampoTamanhoMinimo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A operação &quot;{0}&quot; foi realizada com sucesso..
        /// </summary>
        public static string OperacaoRealizadoComSucesso {
            get {
                return ResourceManager.GetString("OperacaoRealizadoComSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O registro &quot;{0}&quot; já existe na base..
        /// </summary>
        public static string RegistroExistente {
            get {
                return ResourceManager.GetString("RegistroExistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O registro &quot;{0}&quot; não foi encontrado..
        /// </summary>
        public static string RegistroNaoEncontrado {
            get {
                return ResourceManager.GetString("RegistroNaoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O registro &quot;{0}&quot; foi removido..
        /// </summary>
        public static string RegistroRemovido {
            get {
                return ResourceManager.GetString("RegistroRemovido", resourceCulture);
            }
        }
    }
}
